export { default as analyticsRouter } from './analytics.routes';
export { default as categoryRouter } from './category.routes';
export { default as contentRouter } from './content.routes';
export { default as couponRouter } from './coupon.routes';
export { default as courseRouter } from './course.routes';
// export { default as notificationRouter } from "./notification.routes";
// export { default as layoutRouter } from "./layout.routes";
// export { default as mediaRouter } from "./media.routes";
export { default as paymentRouter } from './payment.controller';
// export { default as newUserRouter } from "./new-user.routes";
// export { default as orderRouter } from "./order.routes";
// export { default as paymentRouter } from "./payment.routes";
export { default as progressRouter } from './progress.routes';
// export { default as questionRouter } from "./question.routes";
// export { default as reviewRouter } from "./review.routes";
export { default as userRouter } from './user.routes';
export { default as assignmentSubmissionRouter } from './assignmentSubmission.routes';
// export { default as verificationRouter } from "./verification.routes";
// export { default as zohoRouter } from "./zoho.routes";
export { default as quizSubmission } from './quizSubmission.routes';
export { default as zohoRouter } from './zoho.routes';
